# Generated by Django 2.2.11 on 2020-03-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sflorderline',
            name='quantity',
            field=models.IntegerField(default=100),
        ),
    ]
