# Generated by Django 2.2.11 on 2020-03-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfl', '0002_sflorderline_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sflorderline',
            name='sflProvStatus',
            field=models.CharField(max_length=20),
        ),
    ]
